#!/bin/bash

# Copyright (c) 2014, Gianguido Sorà
# 
# All rights reserved.
# 
# Redistribution and use in source and binary forms, with or without modification,
# are permitted provided that the following conditions are met:
# 
#     * Redistributions of source code must retain the above copyright notice,
#       this list of conditions and the following disclaimer.
#     * Redistributions in binary form must reproduce the above copyright notice,
#       this list of conditions and the following disclaimer in the documentation
#       and/or other materials provided with the distribution.
#     * Neither the name of SafeDrive nor the names of its contributors
#       may be used to endorse or promote products derived from this software
#       without specific prior written permission.
# 
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
# A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR
# CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
# EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
# PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
# PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
# LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
# NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.


checkRoot() {
	if [[ $UID != 0 ]]; then
		echo "Please run this script as root."
		exit 9
	fi
	}

main() {
	checkRoot

	echo -e "Welcome to the SafeDrive creation setup, please provide a name for your SafeDrive.\nUse only dots (.), and underscores (_) if desired, any other illegal character will be stripped automatically.\n"

	read NAME
	NAME=$( echo "$NAME" | tr -d "[<>|/\\\&:?* ]")
	
	echo -e "Your encrypted virtual drive will be created into $PWD, after this setup it will  be safe to move it elsewhere.\n"

	DPATH=$PWD/$NAME
	echo -e "How many M/G/T?"
	read SIZE
	fallocate -l $SIZE $DPATH
	echo -e "Now entering cryptsetup procedure, keep in mind that the password you'll choose (hopefully) cannot be recovered!\nPress enter to begin...\n"
	read AAH

	cryptsetup -c serpent -s 256 -h sha512 --use-urandom luksFormat $DPATH

	echo -e "Mounting the newely created drive...\n"
	cryptsetup open $DPATH $NAME

	echo  -e "Formatting $DPATH in ext4...\n"
	mkfs.ext4 -F -L $NAME /dev/mapper/$NAME > /dev/null
	sleep 5
	cryptsetup luksClose /dev/mapper/$NAME

	echo "Done! Use 'mountcrypt' and 'umountcrypt' to easily mount and unmount your safe drive."
	}

main
